### ISSUE TITLE
    self.bg = "https://static.geetest.com/" + data["slice"].replace("slice", "bg") KeyError: 'slice'

### ISSUE THREAD

**Issue by Meliodas-gpu** [ravizhan/geetest-v4-slide-crack#1]
self.bg = "https://static.geetest.com/" + data["slice"].replace("slice", "bg")
KeyError: 'slice'。不可以用了？

**Comment by ravizhan** [comment]
你确定是滑块验证码？可以提供一下captcha_id吗

**Comment by Meliodas-gpu** [comment]
https://spiderapi.cn/captcha/geetest-v4，captcha_id是4f6147ccd6e9a39ab33608b16e248abc

> 你确定是重启验证码吗？可以提供一下captcha_id吗
